CREATE TABLE auta( 
marka VARCHAR(128) NOT NULL,
model VARCHAR(128) NOT NULL, 
ile_drzwi INTEGER, 
pojemnosc INTEGER, 
rodzaj_paliwa VARCHAR(10), 
ile_koni INTEGER,
kraj_pochodzenia VARCHAR(255)
);

INSERT INTO AUTA(MARKA,MODEL,ILE_DRZWI,POJEMNOSC,RODZAJ_PALIWA,ILE_KONI,KRAJ_POCHODZENIA) VALUES ('VW','Passat, Polo',5,1600,'ON',96,'Niemcy');


INSERT INTO AUTA(MARKA,MODEL,ILE_DRZWI,POJEMNOSC,RODZAJ_PALIWA,ILE_KONI,KRAJ_POCHODZENIA) VALUES ('VW','Golf, Arteon',5,1900,'PB',120,'Niemcy');
INSERT INTO AUTA(MARKA,MODEL,ILE_DRZWI,POJEMNOSC,RODZAJ_PALIWA,ILE_KONI,KRAJ_POCHODZENIA) VALUES ('swidrowiatrak','Polo',3,1900,'PB',120,'Wlochy');


